### ISSUE TITLE
Compilation errors for ESP32

### ISSUE THREAD

**Issue by JabberwockPL** [DFRobot/DFRobot_LedDisplayModule#1]
I have purchased the display and I am trying to use it with my DOIT ESP32 DEVKIT1. However, I get errors when trying to compile (attached). It compiles normally for Arduinos.

[Error.txt](https://github.com/DFRobot/DFRobot_LedDisplayModule/files/6642793/Error.txt)

**Comment by hl68fx** [comment]
I have the same problem, any solution?

**Comment by mariuszmikolajczak** [comment]
Library doesn't compile on ESP32 for me as well:

```
In file included from /Users/mariusz/Documents/Arduino/libraries/DFRobot_LedDisplayModule-master/DFRobot_LedDisplayModule.cpp:15:0:
/Users/mariusz/Documents/Arduino/libraries/DFRobot_LedDisplayModule-master/DFRobot_LedDisplayModule.h:164:10: note: previous specification in 'void DFRobot_LedDisplayModule::print8(const char*, const char*, const char*, const char*, const char*, const char*, const char*, const char*)' here
     void print8(const char buf1[] = "82",const char buf2[] = "82",const char buf3[] = "82",const char buf4[] = "82",const char buf5[] = "82",const char buf6[] = "82",const char buf7[] = "82",const char buf8[] = "82");
          ^
[..]
In file included from /Users/mariusz/Documents/Arduino/libraries/DFRobot_LedDisplayModule-master/DFRobot_LedDisplayModule.cpp:15:0:
/Users/mariusz/Documents/Arduino/libraries/DFRobot_LedDisplayModule-master/DFRobot_LedDisplayModule.h:164:10: note: previous specification in 'void DFRobot_LedDisplayModule::print8(const char*, const char*, const char*, const char*, const char*, const char*, const char*, const char*)' here
     void print8(const char buf1[] = "82",const char buf2[] = "82",const char buf3[] = "82",const char buf4[] = "82",const char buf5[] = "82",const char buf6[] = "82",const char buf7[] = "82",const char buf8[] = "82");
          ^
[..]
/Users/mariusz/Documents/Arduino/libraries/DFRobot_LedDisplayModule-master/DFRobot_LedDisplayModule.cpp:542:18: error: ISO C++ forbids comparison between pointer and integer [-fpermissive]
   if (buf8[0] != "82"){
                  ^
Compilation error: exit status 1}
```

**Comment by tangjie133** [comment]
The problem has been solved.

**Comment by JabberwockPL** [comment]
Now it does not compile either for ESP32 or for Arduino... The error is:

no matching function for call to 'DFRobot_LedDisplayModule::DFRobot_LedDisplayModule(TwoWire&, int)'

**Comment by tangjie133** [comment]
problem has been solved

**Comment by JabberwockPL** [comment]
Unfortunately, I still cannot compile the code, but this might be related to an incompatibility of the Wire library, as users of different modules also sometimes have that problem.

**Comment by JabberwockPL** [comment]
ledPower compiles without problem, while ledPrint throws an error: the difference seems to be:
LED.begin(LED.e4Bit) vs. LED.begin4(LED.e4Bit)

**Comment by JabberwockPL** [comment]
It works now, thanks!
